const keys = ["noteTitle", "noteDue", "noteSaved", "noteFull", "noteEmpty", "noteCancelled", "noteInvalid", "noteTimeInvalid", "noteStorageFailed", "noteChanged", "noteBusy", "noteView", "noteAck", "noteCancel", "noteKeep", "noteReplace", "noteBack", "noteReset", "noteOld", "noteNew", "noteNotice", "notePrivate"];
const rows = {
  "zh-CN": ["一张小纸条", "叮，约好的时间到啦", "记住啦，到时间叫你。", "哎呀呀，脑袋不够用，我只能记一条哦。", "还没有交给我的小纸条。", "好啦，这件事不用记着了。", "没记成功，请把时间和事情再说一次。", "时间没弄清，请说一个明确的未来时间。", "纸条无法安全保存或读取，请重试或清除。", "纸条刚刚变了，请重新查看。", "还在听上一句话，稍等一下。", "已记一条", "收到啦", "取消提醒", "保留原来的", "换成这条", "继续聊天", "清除纸条", "原来", "新的", "你的小纸条到时间啦，打开看看吧。", "提醒会加密保存在这台 Mac；退出期间不会提醒。"],
  "zh-TW": ["一張小紙條", "叮，約好的時間到啦", "記住啦，到時間叫你。", "哎呀呀，腦袋不夠用，我只能記一條哦。", "還沒有交給我的小紙條。", "好啦，這件事不用記著了。", "沒記成功，請把時間和事情再說一次。", "時間沒弄清，請說一個明確的未來時間。", "紙條無法安全儲存或讀取，請重試或清除。", "紙條剛剛變了，請重新查看。", "還在聽上一句話，稍等一下。", "已記一條", "收到啦", "取消提醒", "保留原來的", "換成這條", "繼續聊天", "清除紙條", "原來", "新的", "你的小紙條到時間啦，打開看看吧。", "提醒會加密儲存在這台 Mac；退出期間不會提醒。"],
  en: ["One little note", "Ding! It's time", "Noted. I'll remind you when it's time.", "Tiny head, one note! Which one shall I keep?", "No little note to look after yet.", "All right, I've let that note go.", "Not saved. Please repeat the time and task.", "Please give me a clear time in the future.", "Can't safely save or read the note. Retry or clear it.", "The note changed. Please open it again.", "Still listening to your last message. One moment.", "One note saved", "Got it", "Cancel reminder", "Keep original", "Replace it", "Back to chat", "Clear note", "Original", "New", "Your little note is due. Open it to take a look.", "Encrypted on this Mac. Reminders pause while the app is closed."],
  ja: ["小さなメモ", "約束の時間だよ", "覚えたよ。時間になったら呼ぶね。", "小さな頭だから、一つだけ。どっちを覚える？", "まだ預かったメモはないよ。", "このメモは忘れておくね。", "保存できなかったよ。時間と用件をもう一度。", "これからの時間をはっきり教えてね。", "安全に保存・読込できません。再試行か削除を。", "メモが変わったよ。もう一度開いてね。", "前の言葉を聞いているよ。少し待ってね。", "メモが一つ", "わかった", "通知を取消", "元のまま", "入れ替える", "会話に戻る", "メモを削除", "元のメモ", "新しいメモ", "メモの時間だよ。開いて確認してね。", "このMacに暗号化保存。アプリ終了中は通知しません。"],
  fr: ["Un petit mémo", "Ding ! C'est l'heure", "C'est noté. Je te rappellerai à l'heure.", "Petite tête, un seul mémo ! Lequel garder ?", "Pas encore de petit mémo à garder.", "D'accord, ce mémo est annulé.", "Pas enregistré. Répète l'heure et la tâche.", "Indique une heure future précise.", "Stockage sûr indisponible. Réessaie ou efface.", "Le mémo a changé. Rouvre-le.", "J'écoute encore ton dernier message. Patiente.", "Un mémo gardé", "Bien reçu", "Annuler", "Garder l'ancien", "Remplacer", "Discussion", "Effacer", "Ancien", "Nouveau", "Ton petit mémo est arrivé à échéance. Ouvre-le.", "Chiffré sur ce Mac. Pas de rappel si l'app est fermée."],
  de: ["Ein kleiner Merkzettel", "Ding! Es ist so weit", "Gemerkt. Ich erinnere dich rechtzeitig.", "Kleiner Kopf, ein Zettel! Welchen behalten?", "Noch kein kleiner Zettel für mich.", "Gut, diesen Zettel vergesse ich.", "Nicht gespeichert. Bitte Zeit und Aufgabe nennen.", "Bitte nenne einen klaren Zeitpunkt in der Zukunft.", "Sicheres Speichern nicht möglich. Erneut versuchen.", "Der Zettel hat sich geändert. Bitte erneut öffnen.", "Ich höre noch zu. Einen Moment bitte.", "Ein Zettel da", "Gesehen", "Abbrechen", "Alten behalten", "Ersetzen", "Zum Chat", "Zettel löschen", "Bisher", "Neu", "Dein Merkzettel ist fällig. Öffne ihn zum Nachsehen.", "Verschlüsselt auf diesem Mac. Keine Erinnerung bei geschlossener App."],
  ru: ["Маленькая записка", "Динь! Уже пора", "Запомнил. Напомню, когда придёт время.", "Голова маленькая — записка одна! Какую оставить?", "Пока нет записки, которую нужно беречь.", "Хорошо, эту записку можно забыть.", "Не сохранилось. Повтори время и дело.", "Укажи точное время в будущем.", "Безопасное хранение недоступно. Повтори или удали.", "Записка изменилась. Открой её снова.", "Ещё слушаю прошлое сообщение. Подожди немного.", "Есть записка", "Понятно", "Отменить", "Оставить старую", "Заменить", "К беседе", "Удалить", "Прежняя", "Новая", "Пришло время твоей записки. Открой и посмотри.", "Зашифровано на этом Mac. Закрытое приложение не напоминает."],
};
export const REMINDER_MESSAGES = Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))]));
